server:
  port: 8088
  servlet:
    context-path: /

logging:
  config: classpath:log4j2-spring.xml
  level:
    com.book.retail.dao: debug

spring:
  #mysql
  datasource:
    hikari:
      #池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 20
      #池中维护的最小空闲连接数，最好不设置，和max一致
      #minimum-idle: 10
      data-source-properties: {cachePrepStmts: true,prepStmtCacheSize: 250,prepStmtCacheSqlLimit: 2048}
#    host: 127.0.0.1
#    port: 3306
#    username: root
#    password: mac12345
    #配置h2数据库的连接地址
    # Embedded 嵌入式
    # Remote (client/server) 远程连接
    # In-Memory 内存
    url: jdbc:h2:mem:test
    #配置JDBC Driver
    driver-class-name: org.h2.Driver
    #配置数据库用户名
    username: root
    #配置数据库密码
    password: 123456
    #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
    #schema: src/main/resources/db/schema.sql
    schema: classpath:db/schema.sql
    data: classpath:db/db.sql
    # data: src/main/resources/db/db.sql
  h2:
    console:
      enabled: true
      #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。默认为/h2-console
      path: /h2
      # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #启用SQL语句的日志记录
    show-sql: true




# mybatis_config
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.book.retail.dao
mapper:
  mappers: com.book.retail.domain.base.BookRetailBaseMapper
  not-empty: false
  i-d-e-n-t-i-t-y: MYSQL
#mybatis 分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true

#是否启用swagger
swagger:
  enable: true
